/* tslint:disable */
/* eslint-disable */
/**
 * 租户业务服务
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
import { AdminResultBoolean } from '../models';
import { AdminResultListTenantBusiness } from '../models';
/**
 * TenantBusinessApi - axios parameter creator
 * @export
 */
export const TenantBusinessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 增加租户业务数据
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTenantBusinessAddBusinessPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tenantBusiness/addBusiness`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询租户业务数据
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTenantBusinessGetBusinessListGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tenantBusiness/getBusinessList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TenantBusinessApi - functional programming interface
 * @export
 */
export const TenantBusinessApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 增加租户业务数据
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTenantBusinessAddBusinessPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultBoolean>>> {
            const localVarAxiosArgs = await TenantBusinessApiAxiosParamCreator(configuration).apiTenantBusinessAddBusinessPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 查询租户业务数据
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTenantBusinessGetBusinessListGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListTenantBusiness>>> {
            const localVarAxiosArgs = await TenantBusinessApiAxiosParamCreator(configuration).apiTenantBusinessGetBusinessListGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TenantBusinessApi - factory interface
 * @export
 */
export const TenantBusinessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 增加租户业务数据
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTenantBusinessAddBusinessPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultBoolean>> {
            return TenantBusinessApiFp(configuration).apiTenantBusinessAddBusinessPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 查询租户业务数据
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTenantBusinessGetBusinessListGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListTenantBusiness>> {
            return TenantBusinessApiFp(configuration).apiTenantBusinessGetBusinessListGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TenantBusinessApi - object-oriented interface
 * @export
 * @class TenantBusinessApi
 * @extends {BaseAPI}
 */
export class TenantBusinessApi extends BaseAPI {
    /**
     * 
     * @summary 增加租户业务数据
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantBusinessApi
     */
    public async apiTenantBusinessAddBusinessPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultBoolean>> {
        return TenantBusinessApiFp(this.configuration).apiTenantBusinessAddBusinessPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 查询租户业务数据
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantBusinessApi
     */
    public async apiTenantBusinessGetBusinessListGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListTenantBusiness>> {
        return TenantBusinessApiFp(this.configuration).apiTenantBusinessGetBusinessListGet(options).then((request) => request(this.axios, this.basePath));
    }
}
