/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddMenuInput
 */
export interface AddMenuInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof AddMenuInput
     */
    id: number;
    /**
     * 父Id
     * @type {number}
     * @memberof AddMenuInput
     */
    pid?: number;
    /**
     * 菜单类型（1目录 2菜单 3按钮）
     * @type {number}
     * @memberof AddMenuInput
     */
    type?: number;
    /**
     * 名称
     * @type {string}
     * @memberof AddMenuInput
     */
    name?: string | null;
    /**
     * 路由地址
     * @type {string}
     * @memberof AddMenuInput
     */
    path?: string | null;
    /**
     * 组件路径
     * @type {string}
     * @memberof AddMenuInput
     */
    component?: string | null;
    /**
     * 权限标识
     * @type {string}
     * @memberof AddMenuInput
     */
    permission?: string | null;
    /**
     * 跳转地址
     * @type {string}
     * @memberof AddMenuInput
     */
    redirect?: string | null;
    /**
     * 内嵌地址
     * @type {string}
     * @memberof AddMenuInput
     */
    frameSrc?: string | null;
    /**
     * 图标
     * @type {string}
     * @memberof AddMenuInput
     */
    icon?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof AddMenuInput
     */
    orderNo?: number;
    /**
     * 是否显示
     * @type {boolean}
     * @memberof AddMenuInput
     */
    hideMenu?: boolean;
    /**
     * 是否忽略KeepAlive缓存
     * @type {boolean}
     * @memberof AddMenuInput
     */
    ignoreKeepAlive?: boolean;
    /**
     * 当前激活的菜单-用于配置详情页时左侧激活的菜单路径
     * @type {string}
     * @memberof AddMenuInput
     */
    currentActiveMenu?: string | null;
    /**
     * 标题
     * @type {string}
     * @memberof AddMenuInput
     */
    title: string;
}
