/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddUserInput
 */
export interface AddUserInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof AddUserInput
     */
    id: number;
    /**
     * 密码（默认MD5加密）
     * @type {string}
     * @memberof AddUserInput
     */
    password?: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof AddUserInput
     */
    nickName?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof AddUserInput
     */
    avatar?: string | null;
    /**
     * 出生日期
     * @type {Date}
     * @memberof AddUserInput
     */
    birthday?: Date | null;
    /**
     * 性别
     * @type {number}
     * @memberof AddUserInput
     */
    sex?: number;
    /**
     * 邮箱
     * @type {string}
     * @memberof AddUserInput
     */
    email?: string | null;
    /**
     * 手机号码
     * @type {string}
     * @memberof AddUserInput
     */
    phone?: string | null;
    /**
     * 身份证号
     * @type {string}
     * @memberof AddUserInput
     */
    idCard?: string | null;
    /**
     * 个性签名
     * @type {string}
     * @memberof AddUserInput
     */
    signature?: string | null;
    /**
     * 个人简介
     * @type {string}
     * @memberof AddUserInput
     */
    introduction?: string | null;
    /**
     * 账号类型-超级管理员_1、管理员_2、普通_3
     * @type {number}
     * @memberof AddUserInput
     */
    userType?: number;
    /**
     * 备注
     * @type {string}
     * @memberof AddUserInput
     */
    remark?: string | null;
    /**
     * 状态
     * @type {number}
     * @memberof AddUserInput
     */
    status?: number;
    /**
     * 机构Id
     * @type {number}
     * @memberof AddUserInput
     */
    orgId?: number;
    /**
     * 职位Id
     * @type {number}
     * @memberof AddUserInput
     */
    posId?: number;
    /**
     * 工号
     * @type {string}
     * @memberof AddUserInput
     */
    jobNum?: string | null;
    /**
     * 岗位状态
     * @type {number}
     * @memberof AddUserInput
     */
    jobStatus?: number;
    /**
     * 账号名称
     * @type {string}
     * @memberof AddUserInput
     */
    userName: string;
    /**
     * 真实姓名
     * @type {string}
     * @memberof AddUserInput
     */
    realName: string;
}
