/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SysJobDetail } from './sys-job-detail';
import { SysJobTrigger } from './sys-job-trigger';
/**
 * 
 * @export
 * @interface JobOutput
 */
export interface JobOutput {
    /**
     * 
     * @type {SysJobDetail}
     * @memberof JobOutput
     */
    jobDetail?: SysJobDetail;
    /**
     * 触发器集合
     * @type {Array<SysJobTrigger>}
     * @memberof JobOutput
     */
    jobTriggers?: Array<SysJobTrigger> | null;
}
