/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SysUser } from './sys-user';
/**
 * 代码生成表
 * @export
 * @interface SysCodeGen
 */
export interface SysCodeGen {
    /**
     * 雪花Id
     * @type {number}
     * @memberof SysCodeGen
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysCodeGen
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysCodeGen
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysCodeGen
     */
    createUserId?: number | null;
    /**
     * 
     * @type {SysUser}
     * @memberof SysCodeGen
     */
    createUser?: SysUser;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof SysCodeGen
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysCodeGen
     */
    updateUserId?: number | null;
    /**
     * 
     * @type {SysUser}
     * @memberof SysCodeGen
     */
    updateUser?: SysUser;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof SysCodeGen
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof SysCodeGen
     */
    isDelete?: boolean;
    /**
     * 作者姓名
     * @type {string}
     * @memberof SysCodeGen
     */
    authorName?: string | null;
    /**
     * 是否移除表前缀
     * @type {string}
     * @memberof SysCodeGen
     */
    tablePrefix?: string | null;
    /**
     * 生成方式
     * @type {string}
     * @memberof SysCodeGen
     */
    generateType?: string | null;
    /**
     * 库定位器名
     * @type {string}
     * @memberof SysCodeGen
     */
    configId?: string | null;
    /**
     * 数据库名(保留字段)
     * @type {string}
     * @memberof SysCodeGen
     */
    dbName?: string | null;
    /**
     * 数据库类型
     * @type {string}
     * @memberof SysCodeGen
     */
    dbType?: string | null;
    /**
     * 数据库链接
     * @type {string}
     * @memberof SysCodeGen
     */
    connectionString?: string | null;
    /**
     * 数据库表名
     * @type {string}
     * @memberof SysCodeGen
     */
    tableName?: string | null;
    /**
     * 命名空间
     * @type {string}
     * @memberof SysCodeGen
     */
    nameSpace?: string | null;
    /**
     * 业务名
     * @type {string}
     * @memberof SysCodeGen
     */
    busName?: string | null;
    /**
     * 菜单编码
     * @type {number}
     * @memberof SysCodeGen
     */
    menuPid?: number;
}
