/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DbType } from './db-type';
import { StatusEnum } from './status-enum';
import { SysOrg } from './sys-org';
import { SysUser } from './sys-user';
import { TenantTypeEnum } from './tenant-type-enum';
/**
 * 
 * @export
 * @interface TenantOutput
 */
export interface TenantOutput {
    /**
     * 雪花Id
     * @type {number}
     * @memberof TenantOutput
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof TenantOutput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof TenantOutput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof TenantOutput
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof TenantOutput
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof TenantOutput
     */
    isDelete?: boolean;
    /**
     * 用户Id
     * @type {number}
     * @memberof TenantOutput
     */
    userId?: number;
    /**
     * 
     * @type {SysUser}
     * @memberof TenantOutput
     */
    sysUser?: SysUser;
    /**
     * 机构Id
     * @type {number}
     * @memberof TenantOutput
     */
    orgId?: number;
    /**
     * 
     * @type {SysOrg}
     * @memberof TenantOutput
     */
    sysOrg?: SysOrg;
    /**
     * 主机
     * @type {string}
     * @memberof TenantOutput
     */
    host?: string | null;
    /**
     * 
     * @type {TenantTypeEnum}
     * @memberof TenantOutput
     */
    tenantType?: TenantTypeEnum;
    /**
     * 
     * @type {DbType}
     * @memberof TenantOutput
     */
    dbType?: DbType;
    /**
     * 数据库连接
     * @type {string}
     * @memberof TenantOutput
     */
    connection?: string | null;
    /**
     * 数据库标识
     * @type {string}
     * @memberof TenantOutput
     */
    configId?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof TenantOutput
     */
    order?: number;
    /**
     * 备注
     * @type {string}
     * @memberof TenantOutput
     */
    remark?: string | null;
    /**
     * 
     * @type {StatusEnum}
     * @memberof TenantOutput
     */
    status?: StatusEnum;
    /**
     * 租户名称
     * @type {string}
     * @memberof TenantOutput
     */
    name?: string | null;
    /**
     * 管理员
     * @type {string}
     * @memberof TenantOutput
     */
    adminName?: string | null;
    /**
     * 电子邮箱
     * @type {string}
     * @memberof TenantOutput
     */
    email?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof TenantOutput
     */
    phone?: string | null;
}
