/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RequestTypeEnum } from './request-type-enum';
import { SpareTimeExecuteTypes } from './spare-time-execute-types';
import { SpareTimeTypes } from './spare-time-types';
/**
 * 
 * @export
 * @interface UpdateTimerInput
 */
export interface UpdateTimerInput {
    /**
     * 雪花Id
     * @type {number}
     * @memberof UpdateTimerInput
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof UpdateTimerInput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof UpdateTimerInput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof UpdateTimerInput
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof UpdateTimerInput
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof UpdateTimerInput
     */
    isDelete?: boolean;
    /**
     * 是否只执行一次
     * @type {boolean}
     * @memberof UpdateTimerInput
     */
    doOnce?: boolean;
    /**
     * 是否立即执行
     * @type {boolean}
     * @memberof UpdateTimerInput
     */
    startNow?: boolean;
    /**
     * 
     * @type {SpareTimeExecuteTypes}
     * @memberof UpdateTimerInput
     */
    executeType?: SpareTimeExecuteTypes;
    /**
     * 执行间隔（单位秒）
     * @type {number}
     * @memberof UpdateTimerInput
     */
    interval?: number | null;
    /**
     * Cron表达式
     * @type {string}
     * @memberof UpdateTimerInput
     */
    cron?: string | null;
    /**
     * 
     * @type {SpareTimeTypes}
     * @memberof UpdateTimerInput
     */
    timerType?: SpareTimeTypes;
    /**
     * 请求url
     * @type {string}
     * @memberof UpdateTimerInput
     */
    requestUrl?: string | null;
    /**
     * 
     * @type {RequestTypeEnum}
     * @memberof UpdateTimerInput
     */
    requestType?: RequestTypeEnum;
    /**
     * 请求参数
     * @type {string}
     * @memberof UpdateTimerInput
     */
    requestPara?: string | null;
    /**
     * Headers参数 比如{\"Authorization\":\"userpassword\"}
     * @type {string}
     * @memberof UpdateTimerInput
     */
    headers?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof UpdateTimerInput
     */
    order?: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateTimerInput
     */
    remark?: string | null;
    /**
     * 任务名称
     * @type {string}
     * @memberof UpdateTimerInput
     */
    timerName: string;
}
