/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddMenuInput } from '../models';
import { AdminResultListMenuOutput } from '../models';
import { AdminResultListString } from '../models';
import { AdminResultListSysMenu } from '../models';
import { DeleteMenuInput } from '../models';
import { UpdateMenuInput } from '../models';
/**
 * SysMenuApi - axios parameter creator
 * @export
 */
export const SysMenuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取登录菜单树
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenuListGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getMenuList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取按钮权限列表(登录)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPermCodeGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getPermCode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 增加菜单
         * @param {AddMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sysMenuAddPost: async (body?: AddMenuInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sysMenu/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除菜单
         * @param {DeleteMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sysMenuDeletePost: async (body?: DeleteMenuInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sysMenu/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取菜单列表
         * @param {number} id 主键Id
         * @param {number} [pid] 父Id
         * @param {number} [type] 菜单类型（1目录 2菜单 3按钮）
         * @param {string} [name] 名称
         * @param {string} [path] 路由地址
         * @param {string} [component] 组件路径
         * @param {string} [permission] 权限标识
         * @param {string} [redirect] 跳转地址
         * @param {string} [frameSrc] 内嵌地址
         * @param {string} [title] 标题
         * @param {string} [icon] 图标
         * @param {number} [orderNo] 排序
         * @param {boolean} [hideMenu] 是否显示
         * @param {boolean} [ignoreKeepAlive] 是否忽略KeepAlive缓存
         * @param {string} [currentActiveMenu] 当前激活的菜单-用于配置详情页时左侧激活的菜单路径
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sysMenuListGet: async (id: number, pid?: number, type?: number, name?: string, path?: string, component?: string, permission?: string, redirect?: string, frameSrc?: string, title?: string, icon?: string, orderNo?: number, hideMenu?: boolean, ignoreKeepAlive?: boolean, currentActiveMenu?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling sysMenuListGet.');
            }
            const localVarPath = `/sysMenu/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            if (pid !== undefined) {
                localVarQueryParameter['Pid'] = pid;
            }

            if (type !== undefined) {
                localVarQueryParameter['Type'] = type;
            }

            if (name !== undefined) {
                localVarQueryParameter['Name'] = name;
            }

            if (path !== undefined) {
                localVarQueryParameter['Path'] = path;
            }

            if (component !== undefined) {
                localVarQueryParameter['Component'] = component;
            }

            if (permission !== undefined) {
                localVarQueryParameter['Permission'] = permission;
            }

            if (redirect !== undefined) {
                localVarQueryParameter['Redirect'] = redirect;
            }

            if (frameSrc !== undefined) {
                localVarQueryParameter['FrameSrc'] = frameSrc;
            }

            if (title !== undefined) {
                localVarQueryParameter['Title'] = title;
            }

            if (icon !== undefined) {
                localVarQueryParameter['Icon'] = icon;
            }

            if (orderNo !== undefined) {
                localVarQueryParameter['OrderNo'] = orderNo;
            }

            if (hideMenu !== undefined) {
                localVarQueryParameter['HideMenu'] = hideMenu;
            }

            if (ignoreKeepAlive !== undefined) {
                localVarQueryParameter['IgnoreKeepAlive'] = ignoreKeepAlive;
            }

            if (currentActiveMenu !== undefined) {
                localVarQueryParameter['CurrentActiveMenu'] = currentActiveMenu;
            }

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新菜单
         * @param {UpdateMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sysMenuUpdatePost: async (body?: UpdateMenuInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sysMenu/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SysMenuApi - functional programming interface
 * @export
 */
export const SysMenuApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取登录菜单树
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMenuListGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMenuOutput>>> {
            const localVarAxiosArgs = await SysMenuApiAxiosParamCreator(configuration).getMenuListGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取按钮权限列表(登录)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPermCodeGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListString>>> {
            const localVarAxiosArgs = await SysMenuApiAxiosParamCreator(configuration).getPermCodeGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 增加菜单
         * @param {AddMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuAddPost(body?: AddMenuInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SysMenuApiAxiosParamCreator(configuration).sysMenuAddPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 删除菜单
         * @param {DeleteMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuDeletePost(body?: DeleteMenuInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SysMenuApiAxiosParamCreator(configuration).sysMenuDeletePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取菜单列表
         * @param {number} id 主键Id
         * @param {number} [pid] 父Id
         * @param {number} [type] 菜单类型（1目录 2菜单 3按钮）
         * @param {string} [name] 名称
         * @param {string} [path] 路由地址
         * @param {string} [component] 组件路径
         * @param {string} [permission] 权限标识
         * @param {string} [redirect] 跳转地址
         * @param {string} [frameSrc] 内嵌地址
         * @param {string} [title] 标题
         * @param {string} [icon] 图标
         * @param {number} [orderNo] 排序
         * @param {boolean} [hideMenu] 是否显示
         * @param {boolean} [ignoreKeepAlive] 是否忽略KeepAlive缓存
         * @param {string} [currentActiveMenu] 当前激活的菜单-用于配置详情页时左侧激活的菜单路径
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuListGet(id: number, pid?: number, type?: number, name?: string, path?: string, component?: string, permission?: string, redirect?: string, frameSrc?: string, title?: string, icon?: string, orderNo?: number, hideMenu?: boolean, ignoreKeepAlive?: boolean, currentActiveMenu?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListSysMenu>>> {
            const localVarAxiosArgs = await SysMenuApiAxiosParamCreator(configuration).sysMenuListGet(id, pid, type, name, path, component, permission, redirect, frameSrc, title, icon, orderNo, hideMenu, ignoreKeepAlive, currentActiveMenu, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 更新菜单
         * @param {UpdateMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuUpdatePost(body?: UpdateMenuInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SysMenuApiAxiosParamCreator(configuration).sysMenuUpdatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SysMenuApi - factory interface
 * @export
 */
export const SysMenuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取登录菜单树
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMenuListGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMenuOutput>> {
            return SysMenuApiFp(configuration).getMenuListGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取按钮权限列表(登录)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPermCodeGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListString>> {
            return SysMenuApiFp(configuration).getPermCodeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 增加菜单
         * @param {AddMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuAddPost(body?: AddMenuInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SysMenuApiFp(configuration).sysMenuAddPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除菜单
         * @param {DeleteMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuDeletePost(body?: DeleteMenuInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SysMenuApiFp(configuration).sysMenuDeletePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取菜单列表
         * @param {number} id 主键Id
         * @param {number} [pid] 父Id
         * @param {number} [type] 菜单类型（1目录 2菜单 3按钮）
         * @param {string} [name] 名称
         * @param {string} [path] 路由地址
         * @param {string} [component] 组件路径
         * @param {string} [permission] 权限标识
         * @param {string} [redirect] 跳转地址
         * @param {string} [frameSrc] 内嵌地址
         * @param {string} [title] 标题
         * @param {string} [icon] 图标
         * @param {number} [orderNo] 排序
         * @param {boolean} [hideMenu] 是否显示
         * @param {boolean} [ignoreKeepAlive] 是否忽略KeepAlive缓存
         * @param {string} [currentActiveMenu] 当前激活的菜单-用于配置详情页时左侧激活的菜单路径
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuListGet(id: number, pid?: number, type?: number, name?: string, path?: string, component?: string, permission?: string, redirect?: string, frameSrc?: string, title?: string, icon?: string, orderNo?: number, hideMenu?: boolean, ignoreKeepAlive?: boolean, currentActiveMenu?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListSysMenu>> {
            return SysMenuApiFp(configuration).sysMenuListGet(id, pid, type, name, path, component, permission, redirect, frameSrc, title, icon, orderNo, hideMenu, ignoreKeepAlive, currentActiveMenu, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新菜单
         * @param {UpdateMenuInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sysMenuUpdatePost(body?: UpdateMenuInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SysMenuApiFp(configuration).sysMenuUpdatePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SysMenuApi - object-oriented interface
 * @export
 * @class SysMenuApi
 * @extends {BaseAPI}
 */
export class SysMenuApi extends BaseAPI {
    /**
     * 
     * @summary 获取登录菜单树
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysMenuApi
     */
    public async getMenuListGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMenuOutput>> {
        return SysMenuApiFp(this.configuration).getMenuListGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取按钮权限列表(登录)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysMenuApi
     */
    public async getPermCodeGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListString>> {
        return SysMenuApiFp(this.configuration).getPermCodeGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 增加菜单
     * @param {AddMenuInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysMenuApi
     */
    public async sysMenuAddPost(body?: AddMenuInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SysMenuApiFp(this.configuration).sysMenuAddPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 删除菜单
     * @param {DeleteMenuInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysMenuApi
     */
    public async sysMenuDeletePost(body?: DeleteMenuInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SysMenuApiFp(this.configuration).sysMenuDeletePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取菜单列表
     * @param {number} id 主键Id
     * @param {number} [pid] 父Id
     * @param {number} [type] 菜单类型（1目录 2菜单 3按钮）
     * @param {string} [name] 名称
     * @param {string} [path] 路由地址
     * @param {string} [component] 组件路径
     * @param {string} [permission] 权限标识
     * @param {string} [redirect] 跳转地址
     * @param {string} [frameSrc] 内嵌地址
     * @param {string} [title] 标题
     * @param {string} [icon] 图标
     * @param {number} [orderNo] 排序
     * @param {boolean} [hideMenu] 是否显示
     * @param {boolean} [ignoreKeepAlive] 是否忽略KeepAlive缓存
     * @param {string} [currentActiveMenu] 当前激活的菜单-用于配置详情页时左侧激活的菜单路径
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysMenuApi
     */
    public async sysMenuListGet(id: number, pid?: number, type?: number, name?: string, path?: string, component?: string, permission?: string, redirect?: string, frameSrc?: string, title?: string, icon?: string, orderNo?: number, hideMenu?: boolean, ignoreKeepAlive?: boolean, currentActiveMenu?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListSysMenu>> {
        return SysMenuApiFp(this.configuration).sysMenuListGet(id, pid, type, name, path, component, permission, redirect, frameSrc, title, icon, orderNo, hideMenu, ignoreKeepAlive, currentActiveMenu, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 更新菜单
     * @param {UpdateMenuInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysMenuApi
     */
    public async sysMenuUpdatePost(body?: UpdateMenuInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SysMenuApiFp(this.configuration).sysMenuUpdatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
